version: "3.9"
services:
  app:    
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=person
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=person
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: